### ISSUE TITLE
Persona Login Issues 

### ISSUE THREAD

**Issue by emmairwin** [mozilla/marketpulse#167] opened 2015-05-13 18:54 UTC
Reported by Sucanta Pal

1) Login with Persona (confirm you see a verified message)
2) Confirm that the login screen re-appears (does not redirect to activities)

 I tried to open in different device like smartphone, iPad and also another Computer but problem was same and I check persona its verified successfully.

I could not duplicate.

**Comment by SukantaPal** [comment] 2015-05-13 19:06
Here the Screenshot of Page ![marketpulse page](https://cloud.githubusercontent.com/assets/6872051/7618593/be6ead10-f9d0-11e4-9f42-b39f076fcfff.png)

**Comment by comzeradd** [comment] 2015-05-14 06:53
Hi @SukantaPal, thanks for reporting this.

Since I can't reproduce this could add some details about this? For instance device, os, firefox version.

**Comment by SukantaPal** [comment] 2015-05-14 09:31
Hi @comzeradd,
I tried out computer win and mac, android phone etc. firefox version 37.0.2

**Comment by comzeradd** [comment] 2015-05-14 09:40
Could you check if you get any error messages on the Web Console?

To do this press Shift+Ctrl+K when you are at Marketpulse front page. The Web Console will open at the bottom of your browser screen. There you can keep active the JS, Security, Logging tabs and deactivate the rest. Then try to login with Persona and see if any error message is displayed there.

**Comment by SukantaPal** [comment] 2015-05-14 09:50
Here the screenshot page "Unable to redirect after login failure"
![login failure](https://cloud.githubusercontent.com/assets/6872051/7629703/a0908e54-fa4c-11e4-91b7-3728325ede19.png)

**Comment by SukantaPal** [comment] 2015-05-14 09:53
![server error](https://cloud.githubusercontent.com/assets/6872051/7629773/32c6527c-fa4d-11e4-9bef-b445c6fd130f.png)

**Comment by johngian** [comment] 2015-05-14 09:54
Hey all! Thanks for reporting this. We got a traceback for this and I am investigating why this happens.

**Comment by emmairwin** [comment] 2015-05-14 17:48
@johngian thanks!

**Comment by johngian** [comment] 2015-05-14 18:25
Closing this after #184

**Closed as completed by johngian** 2015-05-14 18:25 UTC

**Comment by SukantaPal** [comment] 2015-06-17 15:34
Facing Same Problem again please look in to this issue @johngian @comzeradd
