### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by sagarhani** [mozilla/marketpulse#191] opened 2015-06-04 19:40 UTC
By clicking on check [this guide](http://education.mozilla-community.org/modules/marketpulse_firefox_os/introduction/)  directs us to **Page not found**.

In this page - https://marketpulse.mozilla.community/activities/

**Comment by comzeradd** [comment] 2015-06-05 08:22
This is already fixed, we'll deploy it today.

Duplicate of #188

**Closed as completed by comzeradd** 2015-06-05 08:22 UTC
